# Generated by Django 3.0 on 2020-04-11 18:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_subject', models.CharField(max_length=100)),
                ('blog_details', models.CharField(max_length=10000)),
                ('blog_image', models.ImageField(upload_to='blog_pics')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track_enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Track_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=100)),
                ('track_description', models.CharField(max_length=10000)),
                ('track_cost', models.IntegerField()),
                ('track_duration', models.IntegerField()),
                ('track_altitude', models.CharField(max_length=100)),
                ('track_difficulty', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('track_length', models.IntegerField()),
                ('track_best_season', models.TextField(max_length=1000)),
                ('track_start_point', models.TextField(max_length=100)),
                ('track_end_point', models.TextField(max_length=100)),
                ('track_railway', models.TextField(max_length=500)),
                ('track_airport', models.TextField(max_length=500)),
                ('track_road', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Track_media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_image', models.ImageField(upload_to='pics')),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.Track_info')),
            ],
        ),
        migrations.CreateModel(
            name='Day_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_description', models.CharField(max_length=10000)),
                ('day', models.IntegerField()),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.Track_info')),
            ],
            options={
                'unique_together': {('track_id', 'day')},
            },
        ),
        migrations.CreateModel(
            name='Track_Season_Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tourism.Season')),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.Track_info')),
            ],
            options={
                'unique_together': {('track_id', 'season_id')},
            },
        ),
        migrations.CreateModel(
            name='Track_Category_Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tourism.Category')),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.Track_info')),
            ],
            options={
                'unique_together': {('track_id', 'category_id')},
            },
        ),
        migrations.CreateModel(
            name='Sub_day_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_description', models.CharField(max_length=10000)),
                ('serial', models.IntegerField()),
                ('day_plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.Day_plan')),
            ],
            options={
                'unique_together': {('day_plan_id', 'serial')},
            },
        ),
    ]
