# Generated by Django 3.0 on 2020-05-01 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('star', models.CharField(max_length=10000)),
                ('photo', models.ImageField(upload_to='review_pics')),
                ('status', models.CharField(max_length=100)),
                ('trek_id', models.CharField(max_length=100)),
                ('trek_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
