# Generated by Django 3.0 on 2020-05-03 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrekkerStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('profile_photo', models.ImageField(upload_to='trekker_story_pics')),
                ('trek_photo', models.ImageField(upload_to='trekker_story_pics')),
                ('status', models.CharField(max_length=100)),
                ('trek_id', models.CharField(max_length=100)),
                ('trek_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
